### PR TITLE
added talk from CSE 491 I gave yesterday

### PR DESCRIPTION
**Pull request by dacb**

### CODE REVIEW

**Comment by arokem** [comment]
Thanks for sharing this! Would you mind adding a license to those slides?

**Comment by dacb** [comment]
No problem, what is the standard mechanism for doing that?

**Comment by arokem** [comment]
The text: 

"2017, Copyright of David Beck, University of Washington. Provided under the CC-BY license" maybe with a link to the license, and a badge like this one:

[License: CC BY 4.0](http://creativecommons.org/licenses/by/4.0/)

(from here: https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba)

Anywhere in the slides. Should do it!

**Comment by arokem** [comment]
Awesome! Thanks.

**Pull request merged**
